/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  Lapangans: () => import('#controllers/lapangans_controller'),
}
